### ISSUE TITLE
onlyoffice nuxeo problem with callbackurl

### ISSUE THREAD

**Issue by mickaelditomaso** [ONLYOFFICE/onlyoffice-nuxeo#11]
Hello, i'm installing the onlyoffice-nuxeo-package.2.0.0 module with an LTS2019.

I have a problem with the callbackurl and the url in https.

I'm accessing Nuxeo with a URL like https://i-gednuxeo.local/nuxeo. When i open a document with onlyoffice, onlyoffice start and give me a error, it can't download the document from Nuxeo. In onlyoffice log, i have a 301 error, because the document is not in http://i-gednuxeo... but in https://i-gednuxeo.....

The connectEditor on Nuxeo is create with adresses in http, not in https. I don't know where is the problem, can you help me.

Thank you

![image](https://user-images.githubusercontent.com/114218436/191917119-5a42bf64-1f62-4693-83e2-3e098ea3f52e.png)

![image](https://user-images.githubusercontent.com/114218436/191917984-98bfb1d2-d6f9-41bf-bfba-e31079e882ae.png)

**Comment by aleksandrfedorov97** [comment]
Hi [mickaelditomaso](https://github.com/mickaelditomaso), could you specify the way you are setting up the https connection? Are you using a proxy service or are you configuring tomcat on https?

**Comment by mickaelditomaso** [comment]
Hi aleksander,

We use a proxy service. Nuxeo say us to use getServerURL instead of getBaseURL with our configuration. It's ok for us. What do think about this?

Thank you

 https://github.com/nuxeo/nuxeo/blob/10.10/nuxeo-webengine/nuxeo-webengine-core/src/main/java/org/nuxeo/ecm/webengine/model/impl/AbstractWebContext.java#L444

**Comment by aleksandrfedorov97** [comment]
We can replace the use of getBaseURL with getServerURL and build for you to try it on your configuration.

**Comment by mickaelditomaso** [comment]
Thank you. Nuxeo send me a package with the correction and it's ok for me. Maybe you can test this correction et provide a new version?

**Comment by aleksandrfedorov97** [comment]
Ok, can you send me this package with the correction?

**Comment by mickaelditomaso** [comment]
[Downloads.zip](https://github.com/ONLYOFFICE/onlyoffice-nuxeo/files/10056460/Downloads.zip)

**Comment by aleksandrfedorov97** [comment]
Thanks [mickaelditomaso](https://github.com/mickaelditomaso) for you contribution, we will make these changes in the next release.
